//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Vehicles
    {
        public short VehicleID { get; set; }
        public string VehicleOwners { get; set; }
        public string VehicleBrand { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleStatus { get; set; }
        public string VehiclePlate { get; set; }
        public string VehicleProblem { get; set; }
    }
}
